global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:8001']
    metrics_path: /metrics

  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant-service:8002']
    metrics_path: /metrics

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8003']
    metrics_path: /metrics

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8004']
    metrics_path: /metrics

  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:8005']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8006']
    metrics_path: /metrics